pipelines:
  default:
    - step:
        #runs-on: self.hosted #uncomment if you want this to run on self-hosted pipelines
        image: mcr.microsoft.com/dotnet/sdk:6.0
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - REPORTS_PATH=./test-reports/build_${BITBUCKET_BUILD_NUMBER}
          - dotnet restore
          - dotnet build --no-restore --configuration Release
          #- dotnet test --no-build --configuration Release --test-adapter-path:. --logger:"junit;LogFilePath=$REPORTS_PATH/junit.xml"
          - dotnet publish Server/Template.Server.csproj -o publish
        artifacts: # defining the artifacts to be passed to each future step.
          - publish/**
    - step:
        #runs-on: self.hosted #uncomment if you want this to run on self-hosted pipelines
        image: atlassian/default-image:2
        name: zip
        script:
          - cd publish
          - zip -r ../publish.zip *
          - cd ../
        artifacts: # defining the artifacts to be passed to each future step.
          - publish.zip
    - step:
        #runs-on: self.hosted #uncomment if you want this to run on self-hosted pipelines
        name: deploy to dev
        deployment: Dev
        script:
          - pipe: microsoft/azure-web-apps-deploy:1.0.0
            variables:
              AZURE_APP_ID: $AZURE_SP_ID
              AZURE_PASSWORD: $AZURE_SP_PASSWORD
              AZURE_TENANT_ID: $AZURE_SP_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_APP_RESOURCE_GROUP
              AZURE_APP_NAME: $AZURE_APP_NAME
              ZIP_FILE: 'publish.zip'

    - step:
        #runs-on: self.hosted #uncomment if you want this to run on self-hosted pipelines
        name: deploy to Test
        deployment: Test
        trigger: manual
        script:
          - pipe: microsoft/azure-web-apps-deploy:1.0.0
            variables:
              AZURE_APP_ID: $AZURE_SP_ID
              AZURE_PASSWORD: $AZURE_SP_PASSWORD
              AZURE_TENANT_ID: $AZURE_SP_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_APP_RESOURCE_GROUP
              AZURE_APP_NAME: $AZURE_APP_NAME
              ZIP_FILE: 'publish.zip'
    - step:
        #runs-on: self.hosted #uncomment if you want this to run on self-hosted pipelines
        name: deploy to Prod
        deployment: Production
        trigger: manual
        script:
          - pipe: microsoft/azure-web-apps-deploy:1.0.0
            variables:
              AZURE_APP_ID: $AZURE_SP_ID
              AZURE_PASSWORD: $AZURE_SP_PASSWORD
              AZURE_TENANT_ID: $AZURE_SP_TENANT_ID
              AZURE_RESOURCE_GROUP: $AZURE_APP_RESOURCE_GROUP
              AZURE_APP_NAME: $AZURE_APP_NAME
              ZIP_FILE: 'publish.zip'